sonar.projectKey=crgolden_Identity
sonar.organization=crgolden

sonar.sources=Identity.Api,Identity.Benchmarks
sonar.tests=Identity.Tests
sonar.exclusions=**/bin/**,**/obj/**

sonar.cs.vscoveragexml.reportsPaths=coverage.xml,coverage-e2e.xml
