namespace Identity.Tests.E2E.AdminLists;

using System.Text.RegularExpressions;
using Duende.IdentityServer.EntityFramework.Entities;
using Identity.Tests.E2E.Infrastructure;

public sealed record ListEditor(
    ListOwnerKind Kind,
    string Section,
    string Collection,
    Regex DetailsUrl,
    Func<string> NewKey,
    string KeyFieldId,
    string? CompanionFieldId,
    Func<string>? NewCompanionValue,
    string ChangedFieldId,
    string RemoveButtonId,
    string RowIdPrefix,
    Func<PlaywrightFixture, string, Task<int>> RowIdByKey,
    Func<PlaywrightFixture, string, Task<int>> RowIdByChangedValue)
{
    public static readonly IReadOnlyList<ListEditor> All =
    [
        new(
            ListOwnerKind.Client,
            nameof(Pages.Admin.Clients),
            nameof(Pages.Admin.Clients.Edit.Claims),
            UrlPatterns.AdminClientsDetailsClaims(),
            Generated.NewClaimType,
            "#claim-type-0",
            "#claim-value-0",
            Generated.NewPropertyValue,
            "#claim-value-0",
            "#claim-remove-0",
            "#claim-row-",
            (fixture, key) => fixture.GetSingleAsync<ClientClaim, int>(c => c.Type == key, c => c.Id),
            (fixture, value) => fixture.GetSingleAsync<ClientClaim, int>(c => c.Value == value, c => c.Id)),
        new(
            ListOwnerKind.Client,
            nameof(Pages.Admin.Clients),
            nameof(Pages.Admin.Clients.Edit.CorsOrigins),
            UrlPatterns.AdminClientsDetailsCorsOrigins(),
            Generated.NewWebsite,
            "#corsorigin-0",
            null,
            null,
            "#corsorigin-0",
            "#corsorigin-remove-0",
            "#cors-origin-row-",
            (fixture, key) => fixture.GetSingleAsync<ClientCorsOrigin, int>(o => o.Origin == key, o => o.Id),
            (fixture, value) => fixture.GetSingleAsync<ClientCorsOrigin, int>(o => o.Origin == value, o => o.Id)),
        new(
            ListOwnerKind.Client,
            nameof(Pages.Admin.Clients),
            nameof(Pages.Admin.Clients.Edit.GrantTypes),
            UrlPatterns.AdminClientsDetailsGrantTypes(),
            Generated.NewToken,
            "#granttype-0",
            null,
            null,
            "#granttype-0",
            "#granttype-remove-0",
            "#grant-type-row-",
            (fixture, key) => fixture.GetSingleAsync<ClientGrantType, int>(g => g.GrantType == key, g => g.Id),
            (fixture, value) => fixture.GetSingleAsync<ClientGrantType, int>(g => g.GrantType == value, g => g.Id)),
        new(
            ListOwnerKind.Client,
            nameof(Pages.Admin.Clients),
            nameof(Pages.Admin.Clients.Edit.IdPRestrictions),
            UrlPatterns.AdminClientsDetailsIdPRestrictions(),
            Generated.NewToken,
            "#idprestriction-0",
            null,
            null,
            "#idprestriction-0",
            "#idprestriction-remove-0",
            "#idp-restriction-row-",
            (fixture, key) => fixture.GetSingleAsync<ClientIdPRestriction, int>(r => r.Provider == key, r => r.Id),
            (fixture, value) => fixture.GetSingleAsync<ClientIdPRestriction, int>(r => r.Provider == value, r => r.Id)),
        new(
            ListOwnerKind.Client,
            nameof(Pages.Admin.Clients),
            nameof(Pages.Admin.Clients.Edit.PostLogoutRedirectUris),
            UrlPatterns.AdminClientsDetailsPostLogoutRedirectUris(),
            Generated.NewWebsite,
            "#postlogoutredirecturi-0",
            null,
            null,
            "#postlogoutredirecturi-0",
            "#postlogoutredirecturi-remove-0",
            "#post-logout-redirect-uri-row-",
            (fixture, key) => fixture.GetSingleAsync<ClientPostLogoutRedirectUri, int>(u => u.PostLogoutRedirectUri == key, u => u.Id),
            (fixture, value) => fixture.GetSingleAsync<ClientPostLogoutRedirectUri, int>(u => u.PostLogoutRedirectUri == value, u => u.Id)),
        new(
            ListOwnerKind.Client,
            nameof(Pages.Admin.Clients),
            nameof(Pages.Admin.Clients.Edit.Properties),
            UrlPatterns.AdminClientsDetailsProperties(),
            Generated.NewAttributeKey,
            "#property-key-0",
            "#property-value-0",
            Generated.NewPropertyValue,
            "#property-value-0",
            "#property-remove-0",
            "#property-row-",
            (fixture, key) => fixture.GetSingleAsync<ClientProperty, int>(p => p.Key == key, p => p.Id),
            (fixture, value) => fixture.GetSingleAsync<ClientProperty, int>(p => p.Value == value, p => p.Id)),
        new(
            ListOwnerKind.Client,
            nameof(Pages.Admin.Clients),
            nameof(Pages.Admin.Clients.Edit.RedirectUris),
            UrlPatterns.AdminClientsDetailsRedirectUris(),
            Generated.NewWebsite,
            "#redirecturi-0",
            null,
            null,
            "#redirecturi-0",
            "#redirecturi-remove-0",
            "#redirect-uri-row-",
            (fixture, key) => fixture.GetSingleAsync<ClientRedirectUri, int>(u => u.RedirectUri == key, u => u.Id),
            (fixture, value) => fixture.GetSingleAsync<ClientRedirectUri, int>(u => u.RedirectUri == value, u => u.Id)),
        new(
            ListOwnerKind.Client,
            nameof(Pages.Admin.Clients),
            nameof(Pages.Admin.Clients.Edit.Scopes),
            UrlPatterns.AdminClientsDetailsScopes(),
            Generated.NewToken,
            "#scope-0",
            null,
            null,
            "#scope-0",
            "#scope-remove-0",
            "#scope-row-",
            (fixture, key) => fixture.GetSingleAsync<ClientScope, int>(s => s.Scope == key, s => s.Id),
            (fixture, value) => fixture.GetSingleAsync<ClientScope, int>(s => s.Scope == value, s => s.Id)),
        new(
            ListOwnerKind.Client,
            nameof(Pages.Admin.Clients),
            nameof(Pages.Admin.Clients.Edit.Secrets),
            UrlPatterns.AdminClientsDetailsSecrets(),
            Generated.NewToken,
            "#secret-description-0",
            "#secret-value-0",
            Generated.NewSecretValue,
            "#secret-description-0",
            "#secret-remove-0",
            "#secret-row-",
            (fixture, key) => fixture.GetSingleAsync<ClientSecret, int>(s => s.Description == key, s => s.Id),
            (fixture, value) => fixture.GetSingleAsync<ClientSecret, int>(s => s.Description == value, s => s.Id)),
        new(
            ListOwnerKind.ApiResource,
            nameof(Pages.Admin.ApiResources),
            nameof(Pages.Admin.ApiResources.Edit.Scopes),
            UrlPatterns.AdminApiResourcesDetailsScopes(),
            Generated.NewToken,
            "#scope-0",
            null,
            null,
            "#scope-0",
            "#scope-remove-0",
            "#scope-row-",
            (fixture, key) => fixture.GetSingleAsync<ApiResourceScope, int>(s => s.Scope == key, s => s.Id),
            (fixture, value) => fixture.GetSingleAsync<ApiResourceScope, int>(s => s.Scope == value, s => s.Id)),
        new(
            ListOwnerKind.ApiResource,
            nameof(Pages.Admin.ApiResources),
            nameof(Pages.Admin.ApiResources.Edit.Secrets),
            UrlPatterns.AdminApiResourcesDetailsSecrets(),
            Generated.NewToken,
            "#secret-description-0",
            "#secret-value-0",
            Generated.NewSecretValue,
            "#secret-description-0",
            "#secret-remove-0",
            "#secret-row-",
            (fixture, key) => fixture.GetSingleAsync<ApiResourceSecret, int>(s => s.Description == key, s => s.Id),
            (fixture, value) => fixture.GetSingleAsync<ApiResourceSecret, int>(s => s.Description == value, s => s.Id)),
        new(
            ListOwnerKind.ApiResource,
            nameof(Pages.Admin.ApiResources),
            nameof(Pages.Admin.ApiResources.Edit.Properties),
            UrlPatterns.AdminApiResourcesDetailsProperties(),
            Generated.NewAttributeKey,
            "#property-key-0",
            "#property-value-0",
            Generated.NewPropertyValue,
            "#property-value-0",
            "#property-remove-0",
            "#property-row-",
            (fixture, key) => fixture.GetSingleAsync<ApiResourceProperty, int>(p => p.Key == key, p => p.Id),
            (fixture, value) => fixture.GetSingleAsync<ApiResourceProperty, int>(p => p.Value == value, p => p.Id)),
        new(
            ListOwnerKind.ApiResource,
            nameof(Pages.Admin.ApiResources),
            nameof(Pages.Admin.ApiResources.Edit.ClaimTypes),
            UrlPatterns.AdminApiResourcesDetailsClaimTypes(),
            Generated.NewClaimType,
            "#claimtype-0",
            null,
            null,
            "#claimtype-0",
            "#claimtype-remove-0",
            "#claim-type-row-",
            (fixture, key) => fixture.GetSingleAsync<ApiResourceClaim, int>(c => c.Type == key, c => c.Id),
            (fixture, value) => fixture.GetSingleAsync<ApiResourceClaim, int>(c => c.Type == value, c => c.Id)),
        new(
            ListOwnerKind.ApiScope,
            nameof(Pages.Admin.ApiScopes),
            nameof(Pages.Admin.ApiScopes.Edit.ClaimTypes),
            UrlPatterns.AdminApiScopesDetailsClaimTypes(),
            Generated.NewClaimType,
            "#claimtype-0",
            null,
            null,
            "#claimtype-0",
            "#claimtype-remove-0",
            "#claim-type-row-",
            (fixture, key) => fixture.GetSingleAsync<ApiScopeClaim, int>(c => c.Type == key, c => c.Id),
            (fixture, value) => fixture.GetSingleAsync<ApiScopeClaim, int>(c => c.Type == value, c => c.Id)),
        new(
            ListOwnerKind.ApiScope,
            nameof(Pages.Admin.ApiScopes),
            nameof(Pages.Admin.ApiScopes.Edit.Properties),
            UrlPatterns.AdminApiScopesDetailsProperties(),
            Generated.NewAttributeKey,
            "#property-key-0",
            "#property-value-0",
            Generated.NewPropertyValue,
            "#property-value-0",
            "#property-remove-0",
            "#property-row-",
            (fixture, key) => fixture.GetSingleAsync<ApiScopeProperty, int>(p => p.Key == key, p => p.Id),
            (fixture, value) => fixture.GetSingleAsync<ApiScopeProperty, int>(p => p.Value == value, p => p.Id)),
        new(
            ListOwnerKind.IdentityResource,
            nameof(Pages.Admin.IdentityResources),
            nameof(Pages.Admin.IdentityResources.Edit.ClaimTypes),
            UrlPatterns.AdminIdentityResourcesDetailsClaimTypes(),
            Generated.NewClaimType,
            "#claimtype-0",
            null,
            null,
            "#claimtype-0",
            "#claimtype-remove-0",
            "#claim-type-row-",
            (fixture, key) => fixture.GetSingleAsync<IdentityResourceClaim, int>(c => c.Type == key, c => c.Id),
            (fixture, value) => fixture.GetSingleAsync<IdentityResourceClaim, int>(c => c.Type == value, c => c.Id)),
        new(
            ListOwnerKind.IdentityResource,
            nameof(Pages.Admin.IdentityResources),
            nameof(Pages.Admin.IdentityResources.Edit.Properties),
            UrlPatterns.AdminIdentityResourcesDetailsProperties(),
            Generated.NewAttributeKey,
            "#property-key-0",
            "#property-value-0",
            Generated.NewPropertyValue,
            "#property-value-0",
            "#property-remove-0",
            "#property-row-",
            (fixture, key) => fixture.GetSingleAsync<IdentityResourceProperty, int>(p => p.Key == key, p => p.Id),
            (fixture, value) => fixture.GetSingleAsync<IdentityResourceProperty, int>(p => p.Value == value, p => p.Id)),
    ];

    public static ListEditor For(ListOwnerKind kind, string collection) =>
        All.Single(editor => editor.Kind == kind && string.Equals(editor.Collection, collection, StringComparison.Ordinal));
}
